 Consider the below code to answer further questions:
 import numpy as np
 list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans. Yes, there is a difference. list_ is a Python list, while array_list is a NumPy array.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [2]:
# Data types of each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Data types of each element in array_list
print("\nData types in array_list:")
for element in array_list:
    print(type(element))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. If array_list is redefined with dtype=int, what will be the data types of elements in list_ and array_list?
Ans.Yes, the data types of the elements in array_list will change to integers, while list_ will still contain strings.

In [4]:
array_list = np.array(object=list_, dtype=int)

# Data types of each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Data types of each element in array_list
print("\nData types in array_list:")
for element in array_list:
    print(type(element))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# Q4. Write a code to find the following characteristics of variable, num_array:(i) shape(ii) size

In [6]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find shape and size
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [7]:
zero_matrix = np.zeros((3, 3))
print("3x3 Matrix with zeros:")
print(zero_matrix)

3x3 Matrix with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
